services:
  window-renderer:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: window-renderer-be
    env_file:
      - src/env/.env.production.local
    volumes:
      - ./logs/window-renderer:/app/dist/logs
    restart: unless-stopped
    command: node dist/index.js
    ports:
      - "5000:5000"