services:
  lb:
    image: "supix/innovaprev_rp"
    container_name: rp
    ports:
      - "80:80"
    networks:
      - fe_nw
      - be_nw
    depends_on:
      - "be"
      - "fe"
  fe:
    image: "supix/innovaprev_fe"
    container_name: fe
    networks:
      - fe_nw
    depends_on:
      - "be"
  be:
    image: "supix/innovaprev_be"
    container_name: be
    networks:
      - be_nw

networks:
  fe_nw:
  be_nw: