services:
  rp:
    image: "supix/innovaprev_rp"
    container_name: rp
    ports:
      - "80:80"
      - "443:443"
    networks:
      - fe_nw
      - be_nw
    restart: unless-stopped
    volumes:
      - ../certs/cert.pem:/etc/ssl/certs/cert.pem
  fe:
    image: "supix/innovaprev_fe"
    container_name: fe
    networks:
      - fe_nw
    restart: unless-stopped
  be:
    image: "supix/innovaprev_be"
    container_name: be
    networks:
      - be_nw
    restart: unless-stopped

networks:
  fe_nw:
  be_nw: