name: Build, publish and deploy backend

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/backend/src/**'
      - 'src/backend/docker/'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/backend/src/**'
      - 'src/backend/docker/'

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ./src/backend/src/
      - name: Build & publish
        run: |
          dotnet build --no-restore ./src/backend/src/
          dotnet publish -c Release ./src/backend/src/
      - name: Build docker image
        run: docker build . -t supix/innovaprev_be:latest -f ./src/backend/docker/Dockerfile
      - name: Publish docker image to Docker hub
        run: |
          docker login -u supix -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push supix/innovaprev_be:latest
      # - name: Pull newly published image and restart the container
      #   uses: appleboy/ssh-action@v1.2.0
      #   with:
      #     host: ${{ secrets.HOST_ADDR }}
      #     username: ${{ secrets.HOST_USER }}
      #     key: ${{ secrets.HOST_KEY }}
      #     script: |
      #       echo ${{ secrets.HOST_PWD }} | sudo -S docker rm -f be
      #       echo ${{ secrets.HOST_PWD }} | sudo -S docker pull supix/innovaprev_be:latest
      #       echo ${{ secrets.HOST_PWD }} | sudo -S docker network inspect be_nw >/dev/null 2>&1 || docker network create be_nw
      #       echo ${{ secrets.HOST_PWD }} | sudo -S docker run -d --network=be_nw --name=be --restart=unless-stopped supix/innovaprev_be:latest