name: Build, publish and deploy backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/backend/src/**'
      - 'src/backend/docker/'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/backend/src/**'
      - 'src/backend/docker/'

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ./src/backend/src/
      - name: Build & publish
        run: |
          dotnet build --no-restore ./src/backend/src/
          dotnet publish -c Release ./src/backend/src/
      - name: Build docker image
        run: docker build . -t supix/innovaprev_be:latest -f ./src/backend/docker/Dockerfile
      - name: Publish docker image to Docker hub
        run: |
          docker login -u supix -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push supix/innovaprev_be:latest
      - name: Deploy to target server
        uses: easingthemes/ssh-deploy@main
        with:
          SCRIPT_BEFORE: |
            docker compose down be
            echo ${{ secrets.HOST_PWD }} | sudo -S su -
          SCRIPT_AFTER: |
            cd prova/trial
            docker compose rm -f be
            docker compose pull be
            docker compose up -d be
          SSH_PRIVATE_KEY: ${{ secrets.HOST_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "src/docker/docker-compose.yml"
          REMOTE_HOST: ${{ secrets.HOST_ADDR }}
          REMOTE_USER: ${{ secrets.HOST_USER }}
          TARGET: "/root/prova/trial/"