name: Frontend deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/frontend/src/**'
      - 'src/frontend/docker/'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/frontend/src/**'
      - 'src/frontend/docker/'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build app and build docker image
        run: docker build . -t supix/innovaprev_fe:latest -f ./src/frontend/docker/Dockerfile.prod
      - name: Publish docker image to Docker hub
        run: |
          docker login -u supix -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push supix/innovaprev_fe:latest
