name: Build, publish and deploy frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/frontend/src/**'
      - 'src/frontend/docker/'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/frontend/src/**'
      - 'src/frontend/docker/'

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build app and build docker image
        run: docker build . -t supix/innovaprev_fe:latest -f ./src/frontend/docker/Dockerfile.prod
      - name: Publish docker image to Docker hub
        run: |
          docker login -u supix -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push supix/innovaprev_fe:latest
      # - name: Deploy to target server
      #   uses: easingthemes/ssh-deploy@main
      #   with:
      #     SCRIPT_BEFORE: |
      #       cd /home/supix/deploy
      #       echo ${{ secrets.HOST_PWD }} | sudo -S docker compose stop
      #       echo ${{ secrets.HOST_PWD }} | sudo -S docker compose rm -f
      #     SCRIPT_AFTER: |
      #       cd /home/supix/deploy
      #       echo ${{ secrets.HOST_PWD }} | sudo -S docker compose pull fe
      #       echo ${{ secrets.HOST_PWD }} | sudo -S docker compose up -d
      #     SSH_PRIVATE_KEY: ${{ secrets.HOST_KEY }}
      #     ARGS: "-rlgoDzvc -i"
      #     SOURCE: "src/docker/"
      #     REMOTE_HOST: ${{ secrets.HOST_ADDR }}
      #     REMOTE_USER: ${{ secrets.HOST_USER }}
      #     TARGET: "/home/supix/deploy"
