name: Build, publish and deploy reverse proxy

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/reverse_proxy/docker/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/reverse_proxy/docker/**'

jobs:
  deploy_reverse_proxy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build . -t supix/innovaprev_rp:latest -f ./src/reverse_proxy/docker/Dockerfile
      - name: Publish docker image to Docker hub
        run: |
          docker login -u supix -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push supix/innovaprev_rp:latest
      # - name: Deploy to target server
      #   uses: easingthemes/ssh-deploy@main
      #   with:
      #     SCRIPT_BEFORE: |
      #       cd /home/supix/deploy
      #       echo ${{ secrets.HOST_PWD }} | sudo -S docker compose stop
      #       echo ${{ secrets.HOST_PWD }} | sudo -S docker compose rm -f
      #     SCRIPT_AFTER: |
      #       cd /home/supix/deploy
      #       echo ${{ secrets.HOST_PWD }} | sudo -S docker compose pull rp
      #       echo ${{ secrets.HOST_PWD }} | sudo -S docker compose up -d
      #     SSH_PRIVATE_KEY: ${{ secrets.HOST_KEY }}
      #     ARGS: "-rlgoDzvc -i"
      #     SOURCE: "src/docker/"
      #     REMOTE_HOST: ${{ secrets.HOST_ADDR }}
      #     REMOTE_USER: ${{ secrets.HOST_USER }}
      #     TARGET: "/home/supix/deploy"