name: Build and publish window renderer

on:
  workflow_dispatch:
  push:
    branches: [ "main", "qa" ]
    paths:
      - 'src/window-renderer/**'
  pull_request:
    branches: [ "main", "qa" ]
    paths:
      - 'src/window-renderer/**'

jobs:
  deploy_window_renderer:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build app and build docker image
        run: docker build . -t supix/innovaprev_wr:latest -f ./src/window-renderer/src/Dockerfile
      - name: Publish docker image to Docker hub
        run: |
          docker login -u supix -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push supix/innovaprev_wr:latest
      - name: Pull newly published image and restart the container
        env:
          WR_CNT_NAME: ${{ github.ref_name == 'qa' && 'wr_qa' || 'wr_prod' }}
          WIR_SERVERURI: ${{ env.WR_CNT_NAME }}:5000
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_ADDR }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          script: |
            echo ${{ secrets.HOST_PWD }} | sudo -S docker rm -f ${{ env.WR_CNT_NAME }}
            echo ${{ secrets.HOST_PWD }} | sudo -S docker pull supix/innovaprev_wr:latest
            echo ${{ secrets.HOST_PWD }} | sudo -S docker run -d --network=wr_nw --name=${{ env.WR_CNT_NAME }} -e NODE_ENV=production -e wir_serverUri=${{ env.WIR_SERVERURI }} --restart=unless-stopped supix/innovaprev_wr:latest
